version: '3.3'

services:
  pgdb:
    image: "postgres:11"
    container_name: "pgdb"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
    networks:
      - common-net
    ports:
      - "54320:5432"
    volumes:
      - /home/slavix/rebrain/db/data:/var/lib/postgresql/data

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - common-net
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    volumes:
      - /home/slavix/rebrain/consul/data:/consul/data

networks:
  common-net:

volumes:
  consul-data:
    driver: local